void mapaInicial();
void apresentaMapa();
void colocarCelula();
int apresentarMenuGeral();
void perguntarMostrarMortosVizinhos();
void apresentarMensagem(const char mens[100]);
void celulavivamorta();
void evoluirJogo(int numGeracoes, int atraso);
void iniciarProcesso();
void mostraLvivo();
void mostraLvizinhasMortas();
