void mapaInicial();
void apresentaMapa();
void colocarCelula();
int apresentarMenuGeral();
void perguntarMostrarMortosVizinhos();
void apresentarMensagem(const char mens[100]);
void evoluirJogo(int numGeracoes, int atraso);
void iniciarProcesso();
void mostraLvivo();
void mostraLvizinhasMortas();
int rconfirma(char pergunta[500]);
void escolheGravacao();
void criarMatriz();
void regrasGerais();
